### ISSUE TITLE
select file by name needed

### ISSUE THREAD

**Issue by System25** [L1L1/cardpeek#68]
Hi, in order to build a LUA script to analyze the Spanish DNIe, I need a card.selectByName(filename) function that sends a PDU like:

   [ 00 A4 04 00 0B 4D 61 73 74 65 72 2E 46 69 6C 65 ]
  SelectFileByName: Master.File
  00 A4 04 00 = Select file by name
  0B = number of bytes of the filename
  4D 61 73 74 65 72 2E 46 69 6C 65 = "Master.File"

I tried to do it myself but cardpeek crashes when I try to send a PDU longer than 8 bytes.

Thank you very much!

**Comment by L1L1** [comment]
Hi, 
The correct way to do this in cardpeek would be to issue the following command:
`
card.select("#4D61737465722E46696C65", 0, "")
`
The two added parameters, **0** and **""**, are here to make sure that no extra zero is added to the command, since cardpeek appends a Le=0 to the select PDU by default otherwise.


You can do the same thing by issuing the send command directly:
`
card.send(bytes.new(8,"00 A4 04 00 0B 4D 61 73 74 65 72 2E 46 69 6C 65"))
`

Nevertheless it seems you found a bug. Normally Cardpeek should not crash when it gets issued a malformed command. An error message should be printed instead. I'll correct this in the next release.

Do not hesitate to contact me if you need any further help.

**Comment by L1L1** [comment]
I will now close this issue.
